name: Deploy to AWS Elastic Beanstalk

on: push

jobs:
  deploy:
    name: deploy-beanstalk
    runs-on: ubuntu-latest

    steps:
      # Setup node, image has v14.16.0
      - name: Use Node.js 12.8.0
        uses: actions/setup-node@v1
        with:
          node-version: 12.8.0

      # Generate unique id for deployment version
      - name: Current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: h-mm-ss
          utcOffset: "+02:00"

      # 1. Checkout code from repository
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Generate artifacts
      - name: Generate deployment package
        run: zip -r deploy.zip * -x "**node_modules**"

      # 3. Deploy to aws elastic beanstalk
      - name: Beanstalk Deploy for app
        uses: einaregilsson/beanstalk-deploy@v16
        with:
          aws_access_key: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws_secret_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          application_name: dan-hola
          environment_name: dan-hola-dev
          region: eu-central-1
          version_label: "version-${{ steps.current-time.outputs.formattedTime }}"
          deployment_package: deploy.zip