name: Deploy AWS Elastic Beanstalk

on: push

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      # Setup node, image has v14.16.0
      - name: Use Node.js 12.8.0
        uses: actions/setup-node@v1
        with:
          node-version: 12.8.0

      # Generate unique id for deployment version
      - name: Current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: h-mm-ss
          utcOffset: "+02:00"

      # 1. Checkout code from repository
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Cache node_modules
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      # 2. Generate artifacts
      - name: Install dependencies
        run: npm install
    
      - name: Run Tests
        run: npm run test
      
      - name: Build artifacts
        run: npm run build

      - name: Generate deployment package
        run: zip -r deploy.zip * -x "**node_modules**"

      # 3. Deploy to aws elastic beanstalk
      - name: Beanstalk Deploy for app
        uses: einaregilsson/beanstalk-deploy@v16
        with:
          aws_access_key: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws_secret_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          application_name: dan-hola
          environment_name: dan-hola-dev
          region: eu-central-1
          version_label: "version-${{ steps.current-time.outputs.formattedTime }}"
          deployment_package: deploy.zip