name: Test

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - run: echo test_dvidoni
      - run: node --version
      - shell: bash
        env: # Or as an environment variable
          SECRET_VAR_DV: ${{ secrets.SECRET_VAR_DV }}
        run: node test.js
      - shell: bash
        env: # Or as an environment variable
          SECRET_VAR_DV: ${{ secrets.SECRET_VAR_DV }}
        run: echo $SUPER_SECRET
